version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - ls
  post_build:
    commands:
      - echo Build completed on `date` !!!
artifacts:
  files:
    - TestAWSLambda-1.0-SNAPSHOT.jar
