version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Build started on `date`
      - export BUCKET=my-bucket-for-test
      - mvn package
      -ls
      -echo hi1
      - mv target/TestAWSLambda-1.0-SNAPSHOT.jar
      -ls
      -echo hi2
      - unzip TestAWSLambda-1.0-SNAPSHOT.jar
      -ls
      -echo hi3
      - rm -rf target src buildspec.yml pom.xml TestAWSLambda-1.0-SNAPSHOT
      -ls
      -echo hi4
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
  post_build:
    commands:
      - echo Build completed on `date` !!!
artifacts:
  files:
    - target/TestAWSLambda-1.0-SNAPSHOT.jar
    - template.yaml
    - outputtemplate.yaml
