version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
      - mv target/TestAWSLambda-1.0-SNAPSHOT.jar .
      - rm -rf target src pom.xml
      - ls
  post_build:
    commands:
      - echo Build completed on `date` !!!
      - aws lambda update-function-code --function-name testAwslambda --zip-file fileb://TestAWSLambda-1.0-SNAPSHOT.jar
artifacts:
  files:
    - TestAWSLambda-1.0-SNAPSHOT.jar
    - ec2.yaml
