AWSTemplateFormatVersion: 2010-09-09
Description: Part 1 - Build a webapp stack with CloudFormation

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09e2d756e7d78558d # ImageID valid only in us-east-1 region
      InstanceType: t2.micro  # aws cloudformation create-stack --stack-name ec2-example --template-body file://ec2.yaml     aws cloudformation delete-stack --stack-name ec2-example
